#!/bin/bash

CWD="$PWD"
ARGV=("$@")
ARGV_=()
OPTS=()
IFS_DEFAULT=$IFS

cd $(dirname $(readlink $0 2>/dev/null || echo $0))
DIRNAME=$PWD
FILENAME=$DIRNAME/$(basename $(readlink $0 2>/dev/null || echo $0))
cd $CWD

__argv_ () {
	while [ $# != 0 ]; do
		if [ "${1:0:1}" = "-" ] && [ "${1:0:1}" != "$1" ]; then
			shift
			[ "${1:0:1}" != "-" ] && shift
		else
			ARGV_+=("$1")
			shift
		fi
	done
}

__argv_ "${ARGV[@]}"

silent () {
	$* > /dev/null 2> /dev/null
	return $?
}

error () {
	if [ "$BASHKIT_COLORS" = "" ]; then
		echo -e $* >&2
	else
		echo -e "\x1B[31m$*\x1B[39m" >&2
	fi
	exit 1
}

not () {
	$* && return 1 || return 0
}

opt-find-def () {
	local IFS=","
	opt-find ${2--} $1
}

opt-find () {
	local default=$1 && shift
	local name=${1//-/}
	local name_opt=opt_$name
	local found=false
	local IFS=$IFS_DEFAULT
	for opt in "$@"; do
		for arg in "${ARGV[@]}"; do
			[ "$opt" = "$arg" ] && found=true && printf -v $name_opt true && continue
			$found && [ "${arg:0:1}" = "-" ] && break 2
			$found && printf -v $name_opt "$arg" && break 2
		done
	done
	for alias in ${@:2}; do
		printf -v opt_alias_${alias//-/} $name
	done
	$found && return 0
	[ "$default" != "-" ] && printf -v $name_opt $default && return 0
	return 1
}

opt () {
	if [ "${1:0:1}" != "-" ]; then
		[ "${ARGV_[0]}" != "$1" ] && return 1
		shift
	fi
	local name=opt_${1//-/}
	[ $# = 1 ] && [ "${!name}" != "" ] && return 0
	OPTS+=(${@//,[^ ]*/})
	for group in "$@"; do
		local IFS="="
		opt-find-def $group
	done
	return $?
}

print-help () {
	local app=$(basename $0)
	local cmds=$(__commands)
	local max=0
	for cmd in $cmds; do
		[ ${#cmd} -gt $max ] && max=${#cmd}
	done
	(
		if [ $max = 0 ]; then
			printf "usage %s <options>\n" $app
		else
			printf "usage: %s <command> [<options>]\n\n" $app
			printf "The available commands are\n"
			for cmd in $cmds; do
				local msg=$(cat $FILENAME | grep cmd-$cmd.\*\# | sed 's/.*#[ ]*//')
				printf "   %-${max}s   %s\n" $cmd "$msg"
			done
			printf "\nRunning '%s --help' will print this message\n" $app
		fi
	) >&2
}

__commands () {
	declare -F | silent grep 'cmd-' || return 1
	declare -F | grep 'cmd-' | sed 's/.*cmd-//' | sed 's/ .*//'
	return $?
}

__autocompletelist () {
	if silent type $@; then
		for word in $($@); do
			echo $word
		done
		exit 0
	fi
}

__autocomplete () {
	if [ "${COMP_CUR:0:1}" = "-" ]; then
		for opt in ${OPTS[@]}; do
			[ "$opt" != "--autocomplete" ] && echo $opt
		done
		exit 0
	fi
	if [ "${COMP_PREV:0:1}" = "-" ] && [ "${#COMP_PREV}" = 2 ]; then
		local opt_alias=opt_alias_${COMP_PREV:1}
		COMP_PREV="--${!opt_alias}"
	fi
	if [ "${COMP_PREV:0:2}" = "--" ]; then
		__autocompletelist tab-opt-${COMP_PREV:2}
		exit 0
	fi

	__autocompletelist tab-${ARGV_[0]}-$(($COMP_CWORD-1))
	__autocompletelist tab-${ARGV_[0]}

	__autocompletelist tab-$COMP_CWORD

	[ "$COMP_CWORD" = "1" ] && __commands && exit 0

	__autocompletelist tab
}

run-shift () {
	if silent type cmd-${ARGV[0]} && silent type sudo-cmd-${ARGV[0]}; then
		ARGV_=("${ARGV_[@]:1}")
		[ ${#ARGV_[@]} = 0 ] && return 0
	else
		ARGV_=("${ARGV_[0]}" "${ARGV_[@]:2}")
		[ ${#ARGV_[@]} = 1 ] && return 0
	fi
	run
}

run () {
	if opt --autocomplete; then
		__autocomplete | grep "^$COMP_CUR"
		return 0
	fi
	if opt --help; then
		print-help
		return 0
	fi
	if silent type cmd-${ARGV_[0]}; then
		cmd-${ARGV_[0]} "${ARGV_[@]:1}"
		return $?
	fi
	if silent type sudo-cmd-${ARGV_[0]}; then
		if [ $EUID = 0 ]; then
			sudo-cmd-${ARGV_[0]} -E "${ARGV_[@]:1}"
		else
			sudo $FILENAME -E "${ARGV[@]}"
		fi
		return $?
	fi
	if silent type cmd; then
		cmd "${ARGV_[@]}"
		return $?
	fi

	print-help
	return 1
}

[ "${BASH_SOURCE[0]}" = "$0" ] || [ "$_" = "$0" ] && . $DIRNAME/cli
