#!/bin/bash
if ! which bashkit > /dev/null 2> /dev/null; then
	printf "__NAME__ requires bashkit which is not installed...\n\n"
	curl -fs https://raw.github.com/mafintosh/bashkit/master/install | bash
	[ $? != 0 ] && exit 1
	printf "\n"
fi
BASHKIT_APP_INSTALL="bashkit install __REPO__"
which __NAME__ > /dev/null 2> /dev/null && BASHKIT_APP_INSTALL="bashkit update __NAME__"
[ ! -O "$(bashkit dirname)/bin" ] && BASHKIT_APP_INSTALL="sudo $BASHKIT_APP_INSTALL"
printf "\x1B[90m$BASHKIT_APP_INSTALL\x1B[39m\n"
$BASHKIT_APP_INSTALL --colors || exit 1
printf "\n__NAME__ is now installed\n"